// Easy-tier vocab hints for Spell It — loaded BEFORE script.js.
// Mirrors the easy tier of words.js. Each entry: meaning + example sentence.
const EASY_DEFS = {
  first: { meaning: "coming before all others", example: "She was first in line for the ride." },
  thought: { meaning: "an idea that comes from thinking", example: "A small thought crossed his mind." },
  years: { meaning: "units of time, each about 365 days", example: "Ten years have passed since then." },
  leave: { meaning: "to go away from a place", example: "Please leave the room now." },
  money: { meaning: "coins and bills used to buy things", example: "He saved his money for a bike." },
  around: { meaning: "in a circle or on all sides", example: "They gathered around the table." },
  place: { meaning: "a particular spot or area", example: "This is my favorite place to read." },
  father: { meaning: "a male parent", example: "Her father taught her to swim." },
  hello: { meaning: "a greeting when you meet someone", example: "Hello, it is nice to see you." },
  believe: { meaning: "to think something is true", example: "I believe what you told me." },
  wanted: { meaning: "desired or hoped for", example: "He wanted the last slice of cake." },
  coming: { meaning: "moving toward or arriving", example: "The bus is coming down the street." },
  house: { meaning: "a building where people live", example: "Their house has a red front door." },
  course: { meaning: "a class, or a route or path", example: "She is taking a course in art." },
  enough: { meaning: "as much as is needed", example: "We have enough food for everyone." },
  mother: { meaning: "a female parent", example: "His mother baked fresh bread." },
  might: { meaning: "maybe; or great strength", example: "You might want to bring a coat." },
  three: { meaning: "the number between two and four", example: "There are three cats in the yard." },
  today: { meaning: "this very day", example: "Today is sunny and warm." },
  listen: { meaning: "to pay attention to a sound", example: "Listen to the birds singing." },
  another: { meaning: "one more, or a different one", example: "May I have another cookie?" },
  talking: { meaning: "speaking with someone", example: "They were talking about school." },
  found: { meaning: "discovered or located", example: "She found her lost key under the couch." },
  getting: { meaning: "receiving or becoming", example: "He is getting better at spelling." },
  looking: { meaning: "turning your eyes toward something", example: "She is looking out the window." },
  morning: { meaning: "the early part of the day", example: "We eat breakfast each morning." },
  trying: { meaning: "making an effort to do something", example: "He is trying to reach the top shelf." },
  family: { meaning: "a group of related people", example: "Our family eats dinner together." },
  without: { meaning: "not having or including", example: "She left without saying goodbye." },
  already: { meaning: "before now", example: "The movie had already started." },
  heard: { meaning: "perceived with the ears", example: "We heard thunder in the distance." },
  ready: { meaning: "prepared to do something", example: "Are you ready to play?" },
  called: { meaning: "named, or shouted to someone", example: "The puppy is called Biscuit." },
  happy: { meaning: "feeling pleasure or joy", example: "The good news made her happy." },
  brother: { meaning: "a male sibling", example: "His brother is two years older." },
  pretty: { meaning: "pleasant to look at", example: "The garden is full of pretty flowers." },
  whole: { meaning: "complete, with nothing missing", example: "She ate the whole sandwich." },
  start: { meaning: "to begin something", example: "Let's start the race at noon." },
  guess: { meaning: "to answer without being sure", example: "Take a guess at the answer." },
  matter: { meaning: "to be important; or a subject", example: "Does it matter who goes first?" },
  bring: { meaning: "to carry something to a place", example: "Bring your umbrella today." },
  tonight: { meaning: "the evening or night of today", example: "We have a game tonight." },
  alone: { meaning: "with no one else", example: "She likes to read alone." },
  school: { meaning: "a place where students learn", example: "We walk to school together." },
  saying: { meaning: "speaking words; or a wise phrase", example: "She keeps saying she is tired." },
  phone: { meaning: "a device used to call people", example: "The phone rang during dinner." },
  looks: { meaning: "seems, or one's appearance", example: "He looks happy today." },
  problem: { meaning: "something that needs to be solved", example: "That math problem is tricky." },
  friends: { meaning: "people you like and trust", example: "My friends and I play after school." },
  anyone: { meaning: "any person", example: "Can anyone answer this question?" },
  killed: { meaning: "caused to die", example: "The storm killed several trees." },
  police: { meaning: "people who keep order and safety", example: "The police helped find the lost dog." },
  excuse: { meaning: "a reason given for doing something", example: "She made an excuse for being late." },
  wants: { meaning: "desires something", example: "He wants a new backpack." },
  heart: { meaning: "the organ that pumps blood", example: "Her heart beats fast after running." },
  worry: { meaning: "to feel nervous or concerned", example: "Don't worry about the test." },
  later: { meaning: "at a time after now", example: "I will call you later." },
  watch: { meaning: "to look at; or a timepiece", example: "We watch the stars at night." },
  music: { meaning: "pleasant sounds made by voices or instruments", example: "Music filled the room." },
  doctor: { meaning: "someone who treats sick people", example: "The doctor checked my throat." },
  young: { meaning: "having lived for only a little time", example: "The young puppy loves to play." },
  second: { meaning: "after the first; or a unit of time", example: "She came in second place." },
  working: { meaning: "doing a job or activity", example: "Dad is working in the garden." },
  water: { meaning: "the clear liquid we drink", example: "Plants need water to grow." },
  stuff: { meaning: "things or materials", example: "Pack your stuff for the trip." },
  exactly: { meaning: "in every detail, precisely", example: "That is exactly what I meant." },
  death: { meaning: "the end of life", example: "The book tells of the plant's death." },
  minute: { meaning: "a unit of time equal to sixty seconds", example: "The train leaves in one minute." },
  crazy: { meaning: "very unusual or wild", example: "That was a crazy roller coaster!" },
  forget: { meaning: "to fail to remember", example: "Don't forget your homework." },
  change: { meaning: "to make different; or loose coins", example: "Please change your shirt." },
  happen: { meaning: "to take place or occur", example: "What will happen next?" },
  drink: { meaning: "to swallow a liquid", example: "Drink some water after the game." },
  knows: { meaning: "understands or is aware", example: "She knows all the answers." },
  taking: { meaning: "carrying or grabbing something", example: "He is taking the bus home." },
  times: { meaning: "multiplied by; or moments", example: "She has been there many times." },
  check: { meaning: "to look at to be sure", example: "Check your work before turning it in." },
  hands: { meaning: "the parts at the end of your arms", example: "Wash your hands before lunch." },
  minutes: { meaning: "units of time, each sixty seconds", example: "The show lasts thirty minutes." },
  means: { meaning: "stands for; or a way of doing something", example: "Red means stop at the light." },
  point: { meaning: "a sharp end, or a score", example: "She scored a point for the team." },
  inside: { meaning: "in the inner part of something", example: "The key is inside the drawer." },
  makes: { meaning: "creates or causes", example: "Sunlight makes plants grow." },
  asked: { meaning: "said a question to someone", example: "She asked where the library was." },
  making: { meaning: "creating or building something", example: "We are making a card for Grandma." },
  afraid: { meaning: "feeling fear or scared", example: "He is afraid of the dark." },
  sleep: { meaning: "to rest with eyes closed", example: "Babies sleep a lot." },
  chance: { meaning: "an opportunity, or luck", example: "Give me a chance to try." },
  quite: { meaning: "very, or completely", example: "It is quite cold outside now." },
  anyway: { meaning: "in any case; regardless", example: "We went anyway, despite the rain." },
  close: { meaning: "near; or to shut", example: "Please close the window." },
  party: { meaning: "a gathering for fun", example: "We gave her a surprise party." },
  against: { meaning: "in opposition to, or touching", example: "The ladder leaned against the wall." },
  comes: { meaning: "arrives or moves this way", example: "Spring comes after winter." },
  shall: { meaning: "will (used to say what will happen)", example: "We shall see what happens." },
  story: { meaning: "a tale or account of events", example: "Grandpa told us a funny story." },
  number: { meaning: "a symbol used to count", example: "Seven is my lucky number." },
  least: { meaning: "the smallest amount", example: "Give the least amount of noise." },
  waiting: { meaning: "staying until something happens", example: "She is waiting for the bus." },
  moment: { meaning: "a very short amount of time", example: "Wait a moment, please." },
  fight: { meaning: "to struggle or battle", example: "The two teams fought for the win." },
  husband: { meaning: "a married man", example: "Her husband cooked dinner Sunday." },
  girls: { meaning: "female children", example: "The girls played hopscotch." },
  married: { meaning: "joined as spouses", example: "They got married in June." },
  nobody: { meaning: "no person at all", example: "Nobody was home when we arrived." },
  stand: { meaning: "to be upright on your feet", example: "Please stand for the song." },
  started: { meaning: "began", example: "The race started at noon." },
  sister: { meaning: "a female sibling", example: "My sister and I share a room." },
  between: { meaning: "in the middle of two things", example: "The cat sat between the two chairs." },
  hours: { meaning: "units of time, each sixty minutes", example: "We waited for two hours." },
  speak: { meaning: "to say words, to talk", example: "Please speak clearly and slowly." },
  women: { meaning: "female adults", example: "The women talked by the gate." },
  behind: { meaning: "at the back of something", example: "The sun went behind the clouds." },
  almost: { meaning: "nearly but not quite", example: "It is almost time for lunch." },
  truth: { meaning: "what is real and true", example: "Always tell the truth." },
  blood: { meaning: "the red liquid in the body", example: "Blood carries oxygen to the body." },
  anymore: { meaning: "no longer; any longer", example: "We don't play that game anymore." },
  playing: { meaning: "having fun with games", example: "The children are playing outside." },
  reason: { meaning: "cause or explanation", example: "What is the reason for your smile?" },
  trouble: { meaning: "difficulty or problems", example: "The puppy got into trouble." },
  break: { meaning: "to smash; or a short rest", example: "Be careful not to break the glass." },
  trust: { meaning: "to believe in someone's honesty", example: "I trust you with my secret." },
  office: { meaning: "a room or building for work", example: "The doctor is in her office." },
  brought: { meaning: "carried here from somewhere", example: "She brought snacks for everyone." },
  welcome: { meaning: "greeted kindly; a greeting", example: "Welcome to our home!" },
  couple: { meaning: "two things or people", example: "A couple of birds sat on the fence." },
  either: { meaning: "one or the other", example: "You can choose either color." },
  seems: { meaning: "appears to be", example: "It seems like it may rain." },
  power: { meaning: "energy, or control and strength", example: "The power went out in the storm." },
  telling: { meaning: "saying something to someone", example: "She is telling us a story." },
  honey: { meaning: "sweet liquid made by bees", example: "She put honey on her toast." },
  tried: { meaning: "made an attempt", example: "He tried his best on the test." },
  front: { meaning: "the part that faces forward", example: "Sit in the front row." },
  answer: { meaning: "a reply to a question", example: "What is the answer to number three?" },
  stupid: { meaning: "lacking sense; unwise", example: "That was a silly, stupid mistake." },
  hurry: { meaning: "to move or act quickly", example: "Hurry, or we will miss the bus!" },
  months: { meaning: "units of time, about thirty days", example: "Summer lasts three months." },
  become: { meaning: "to grow or change into", example: "She wants to become a teacher." },
  along: { meaning: "moving forward; beside", example: "We walked along the river." },
  outside: { meaning: "in the open air, not indoors", example: "The kids are playing outside." },
  light: { meaning: "brightness from the sun or lamps", example: "Turn on the light, please." },
  needs: { meaning: "must have something", example: "Every plant needs water." },
  country: { meaning: "a nation; or land outside cities", example: "Canada is a big country." },
  clear: { meaning: "easy to see or understand", example: "The teacher made it clear." },
  order: { meaning: "arrangement; or a request for food", example: "Line up in the right order." },
  captain: { meaning: "the leader of a team or ship", example: "The captain steered the boat." },
  funny: { meaning: "causing laughter", example: "He told a funny joke." },
  black: { meaning: "the darkest color", example: "She wore a black hat." },
  alive: { meaning: "living, not dead", example: "The fish were still alive." },
  feeling: { meaning: "an emotion or sensation", example: "She had a happy feeling inside." },
  living: { meaning: "being alive; or earning a life", example: "He earns a living as a baker." },
  cause: { meaning: "the reason something happens", example: "Rain is the cause of the wet ground." },
  ahead: { meaning: "in front; moving forward", example: "The finish line is straight ahead." },
  dinner: { meaning: "the main evening meal", example: "We eat dinner at six." },
  sighs: { meaning: "breathes out with a sound", example: "She sighs when she is tired." },
  leaving: { meaning: "going away from a place", example: "They are leaving for the airport." },
  running: { meaning: "moving fast on foot", example: "He is running toward the goal." },
  alright: { meaning: "okay; acceptable", example: "Is everything alright?" },
  promise: { meaning: "to say you will do something", example: "I promise to help you." },
  taken: { meaning: "carried away; captured", example: "The photo was taken yesterday." },
  white: { meaning: "the color of snow", example: "A white cloud floated by." },
  anybody: { meaning: "any person at all", example: "Did anybody see my keys?" },
  small: { meaning: "little in size", example: "A small mouse ran across the floor." },
  perfect: { meaning: "without any flaws", example: "The spelling test was perfect." },
  lives: { meaning: "is alive; or places to live", example: "She lives near the park." },
  special: { meaning: "more important than usual", example: "Today is a special day." },
  parents: { meaning: "mothers and fathers", example: "Her parents came to the show." },
  himself: { meaning: "that same male person", example: "He made lunch himself." },
  perhaps: { meaning: "maybe; possibly", example: "Perhaps we will go to the beach." },
  sounds: { meaning: "noises; or seems like", example: "The bird sounds happy." },
  serious: { meaning: "grave, not joking", example: "He made a serious promise." },
  company: { meaning: "a business; or guests", example: "We have company coming over." },
  scared: { meaning: "frightened", example: "The loud noise made her scared." },
  uncle: { meaning: "the brother of a parent", example: "My uncle teaches music." },
  earth: { meaning: "the planet we live on", example: "Earth orbits the sun." },
  shoot: { meaning: "to fire a gun; to aim", example: "He learned to shoot a bow." },
  touch: { meaning: "to press with your fingers", example: "Don't touch the hot pan." },
  sound: { meaning: "something you can hear", example: "I heard a strange sound." },
  laughs: { meaning: "makes happy sounds", example: "She laughs at his jokes." },
  cannot: { meaning: "are not able to", example: "I cannot reach the top shelf." },
  asking: { meaning: "putting a question", example: "She is asking for help." },
  control: { meaning: "power to manage or guide", example: "He stays in control of the car." },
  human: { meaning: "a person; like a person", example: "Every human needs to sleep." },
  drive: { meaning: "to steer a vehicle", example: "Dad will drive us to school." },
  murder: { meaning: "the crime of killing someone", example: "The book is about a murder mystery." },
  happens: { meaning: "takes place", example: "What happens if I press this button?" },
  daddy: { meaning: "a word for father", example: "Daddy reads me stories." },
  finally: { meaning: "at last; after a long time", example: "The train finally arrived." },
  words: { meaning: "units of speech or writing", example: "The poem has only ten words." },
  street: { meaning: "a road in a town with homes", example: "We live on a quiet street." },
  dance: { meaning: "to move to music", example: "They dance at the party." },
  meeting: { meaning: "a gathering of people", example: "The meeting starts at nine." },
  others: { meaning: "different people or things", example: "Help others when you can." },
  catch: { meaning: "to grab something in motion", example: "Can you catch the ball?" },
  follow: { meaning: "to go or come after", example: "Follow the path to the lake." },
  sense: { meaning: "to feel; or a meaning", example: "I sense something is wrong." },
  evening: { meaning: "the later part of the day", example: "We watch TV in the evening." },
  master: { meaning: "an expert, or a leader", example: "He is a master of chess." },
  known: { meaning: "recognized or familiar", example: "She is known for her singing." },
  dream: { meaning: "images in sleep; a hope", example: "She had a dream about flying." },
  write: { meaning: "to form letters and words", example: "Write your name at the top." },
  million: { meaning: "one thousand thousands", example: "A million stars filled the sky." },
  voice: { meaning: "the sound you make speaking", example: "Her voice was soft and clear." },
  sweet: { meaning: "tasting like sugar", example: "The grapes are very sweet." },
  rather: { meaning: "preferably; or somewhat", example: "I would rather read than watch TV." },
  lucky: { meaning: "having good fortune", example: "You are lucky to find that coin." },
  jesus: { meaning: "a name, especially of Jesus Christ", example: "The church tells stories about Jesus." },
  longer: { meaning: "greater in length", example: "The days are getting longer." },
  calling: { meaning: "shouting or phoning someone", example: "She is calling your name." },
  worked: { meaning: "did work; functioned", example: "He worked at the store all summer." },
  quiet: { meaning: "making little or no noise", example: "Please be quiet in the library." },
  looked: { meaning: "used your eyes to see", example: "She looked out the window." },
  careful: { meaning: "giving attention to avoid harm", example: "Be careful with the scissors." },
  coffee: { meaning: "a hot drink made from beans", example: "Mom drinks coffee every morning." },
  return: { meaning: "to come or go back", example: "I will return the book tomorrow." },
  secret: { meaning: "hidden, kept from others", example: "She kept the surprise a secret." },
  weeks: { meaning: "units of seven days", example: "School starts in two weeks." },
  seeing: { meaning: "using your eyes; meeting", example: "I am seeing the ocean for the first time." },
  given: { meaning: "handed over; provided", example: "He was given a new pencil." },
  fault: { meaning: "a mistake or blame", example: "It was not your fault." },
  takes: { meaning: "grabs or carries", example: "The bus takes an hour." },
  future: { meaning: "the time that is yet to come", example: "Let's plan for the future." },
  loved: { meaning: "cared for deeply", example: "The dog loved his family." },
  changed: { meaning: "made different", example: "The weather changed in an hour." },
  turned: { meaning: "rotated or changed direction", example: "She turned the page." },
  ladies: { meaning: "polite words for women", example: "The ladies sat near the window." },
  learn: { meaning: "to gain knowledge or skill", example: "We learn new words each day." },
  explain: { meaning: "to make something clear", example: "Can you explain the rules?" },
  clean: { meaning: "free of dirt", example: "The kitchen is clean now." },
  piece: { meaning: "a part or portion", example: "May I have a piece of cake?" },
  throw: { meaning: "to send through the air", example: "Throw the ball to me." },
  picture: { meaning: "a drawing, painting, or photo", example: "She drew a picture of a cat." },
  wonder: { meaning: "to think with curiosity", example: "I wonder why the sky is blue." },
  worth: { meaning: "having a certain value", example: "This old coin is worth a lot." },
  darling: { meaning: "a loved one; very dear", example: "Good night, darling." },
  giving: { meaning: "handing something to someone", example: "She is giving her seat away." },
  quick: { meaning: "fast; not slow", example: "Take a quick look outside." },
  moving: { meaning: "changing position", example: "The train is moving fast." },
  figure: { meaning: "a number; or a shape", example: "Add up each figure." },
  state: { meaning: "a country or its region", example: "Texas is a large state." },
  strong: { meaning: "having great power", example: "The strong wind bent the tree." },
  amazing: { meaning: "very wonderful; astonishing", example: "The magic trick was amazing." },
  works: { meaning: "functions; or a place of work", example: "The clock works again." },
  needed: { meaning: "was required", example: "He needed more tape." },
  weird: { meaning: "strange or unusual", example: "That is a weird noise." },
  worried: { meaning: "feeling anxious", example: "She worried about the test." },
  report: { meaning: "a written account", example: "He wrote a report on whales." },
  goodbye: { meaning: "a word said when leaving", example: "She waved goodbye at the door." },
  missing: { meaning: "gone; not where it should be", example: "My sock is missing." },
  choice: { meaning: "the act of choosing", example: "You have a choice of two colors." },
  chief: { meaning: "the leader or main one", example: "The chief of police gave a speech." },
  wedding: { meaning: "a ceremony where two marry", example: "The wedding was in June." },
  strange: { meaning: "unusual or unfamiliar", example: "A strange bird landed in the yard." },
  general: { meaning: "usual; or a high army leader", example: "The general gave orders." },
  kidding: { meaning: "joking; fooling around", example: "No kidding, it really happened." },
  decided: { meaning: "made up your mind", example: "She decided to go to camp." },
  tired: { meaning: "needing rest or sleep", example: "The long walk made us tired." },
  class: { meaning: "a group of students", example: "Our class read a book together." },
  officer: { meaning: "a person with authority", example: "The officer waved at us." },
  worse: { meaning: "less good than before", example: "The rain got worse." },
  mistake: { meaning: "an error", example: "I made a mistake in the sum." },
  court: { meaning: "a place for trials; a play area", example: "Let's meet on the tennis court." },
  finish: { meaning: "to complete something", example: "Finish your lunch first." },
  during: { meaning: "while something happens", example: "I read during the ride." },
  caught: { meaning: "grabbed; captured", example: "She caught the ball at the wall." },
  marry: { meaning: "to join as spouses", example: "They plan to marry in the spring." },
  meant: { meaning: "intended; signified", example: "I did not mean to scare you." },
  system: { meaning: "a group of parts working together", example: "The school uses a new grading system." },
  suppose: { meaning: "to assume or expect", example: "I suppose we can go." },
  movie: { meaning: "a film shown in a theater", example: "We watched a movie last night." },
  mouth: { meaning: "the opening we speak and eat with", example: "Open your mouth and smile." },
  totally: { meaning: "completely; entirely", example: "That is totally true." },
  forgive: { meaning: "to stop being angry at someone", example: "Please forgive me for the mess." },
  imagine: { meaning: "to form a mental picture", example: "Imagine you are on the moon." },
  instead: { meaning: "in place of something", example: "Have juice instead of soda." },
  month: { meaning: "one of the twelve parts of a year", example: "April is my favorite month." },
  lying: { meaning: "not telling the truth; resting flat", example: "He was lying about the dog." },
  unless: { meaning: "except if", example: "You cannot go unless you are ready." },
  train: { meaning: "a long line of cars on rails", example: "The train stopped at the station." },
  seven: { meaning: "the number after six", example: "There are seven days in a week." },
  clothes: { meaning: "things worn on the body", example: "She folded her clothes." },
  michael: { meaning: "a boy's name", example: "Michael rides his bike to school." },
  hotel: { meaning: "a place that rents rooms", example: "We stayed in a hotel by the sea." },
  attack: { meaning: "to act with force against", example: "The dogs attacked the stranger." },
  round: { meaning: "shaped like a circle", example: "The ball is round." },
  expect: { meaning: "to think something will happen", example: "I expect guests at noon." },
  george: { meaning: "a boy's name", example: "George planted a garden." },
  history: { meaning: "the study of the past", example: "We learned about history in school." },
  broke: { meaning: "smashed; ran out", example: "The glass broke on the floor." },
  station: { meaning: "a stopping place, as for trains", example: "Meet me at the station." },
  forever: { meaning: "for all time", example: "I will remember this trip forever." },
  david: { meaning: "a boy's name", example: "David has a red backpack." },
  frank: { meaning: "honest and direct; a name", example: "Frank told the truth plainly." },
  except: { meaning: "not including; apart from", example: "Everyone came except Liam." },
  thinks: { meaning: "believes or considers", example: "She thinks the test was easy." },
  message: { meaning: "words sent to someone", example: "He left a message on the door." },
  entire: { meaning: "whole; complete", example: "The entire class passed." },
  table: { meaning: "furniture with a flat top", example: "The keys are on the table." },
  talked: { meaning: "spoke with someone", example: "We talked about our plans." },
  across: { meaning: "from one side to the other", example: "She swam across the pond." },
  lovely: { meaning: "beautiful; very pleasant", example: "What a lovely sunset!" },
  handle: { meaning: "to manage; or a part you hold", example: "I can handle this job." },
  middle: { meaning: "the center part", example: "The dog slept in the middle of the bed." },
  buddy: { meaning: "a close friend", example: "My buddy and I walked home." },
  protect: { meaning: "to keep someone safe", example: "A fence protects the garden." },
  using: { meaning: "making use of something", example: "She is using my pencil." },
  floor: { meaning: "the surface you stand on", example: "The ball rolled across the floor." },
  swear: { meaning: "to promise seriously", example: "I swear I will be on time." },
  spend: { meaning: "to use money or time", example: "We spend Sunday at the park." },
  bought: { meaning: "paid for and received", example: "He bought milk at the store." },
  letter: { meaning: "a written sign; a mailed note", example: "The word CAT has three letters." },
  simple: { meaning: "easy; not complicated", example: "This is a simple puzzle." },
  space: { meaning: "the area beyond Earth; empty room", example: "Rockets travel into space." },
  group: { meaning: "a number of people together", example: "A group of kids played kickball." },
  single: { meaning: "only one; one alone", example: "A single star shone brightly." },
  sitting: { meaning: "resting with the body upright", example: "The cat is sitting on the mat." },
  peace: { meaning: "calm; freedom from war", example: "We all want peace." },
  forgot: { meaning: "failed to remember", example: "I forgot my umbrella again." },
  force: { meaning: "strength or power", example: "The wind had great force." },
  short: { meaning: "not long or tall", example: "He wears short sleeves." },
  normal: { meaning: "usual; not strange", example: "That is normal for a baby." },
  charlie: { meaning: "a boy's or girl's name", example: "Charlie feeds the ducks." },
  present: { meaning: "a gift; being here", example: "Everyone was present at the party." },
  enjoy: { meaning: "to take pleasure in", example: "I enjoy reading comic books." },
  crime: { meaning: "an act against the law", example: "Stealing is a crime." },
  horse: { meaning: "a large animal people ride", example: "The horse trotted down the trail." },
  ground: { meaning: "the solid surface of the earth", example: "Leaves covered the ground." },
  count: { meaning: "to say numbers in order", example: "Count to ten quietly." },
  charge: { meaning: "the price; to attack; battery power", example: "There is a charge for parking." },
  honor: { meaning: "great respect", example: "It is an honor to meet you." },
  lunch: { meaning: "the midday meal", example: "We had soup for lunch." },
  miles: { meaning: "units of distance, 5280 feet each", example: "We walked three miles." },
  radio: { meaning: "a device that plays broadcast sound", example: "The radio played our favorite song." },
};