// Hard-tier vocab hints for Spell It — loaded BEFORE script.js.
// Mirrors the hard tier of words.js. Each entry: meaning + example sentence.
const HARD_DEFS = {
  filibuster: { meaning: "a long speech meant to block a law", example: "The senator used a filibuster to delay the vote." },
  wrangling: { meaning: "arguing or managing with difficulty", example: "He spent hours wrangling with the budget." },
  sterility: { meaning: "the state of being unable to have young; being germ-free", example: "Lab tools are kept in sterility." },
  provocateur: { meaning: "someone who stirs up trouble on purpose", example: "The agent acted as an provocateur at the rally." },
  periwinkle: { meaning: "a blue-violet color; a small flower", example: "She painted the fence periwinkle." },
  decrypted: { meaning: "turned secret code back into readable text", example: "The team decrypted the hidden message." },
  lumberjacks: { meaning: "people whose job is cutting down trees", example: "Lumberjacks worked in the snowy forest." },
  unappealing: { meaning: "not attractive or pleasant", example: "Cold soup is unappealing." },
  frivolity: { meaning: "silliness; lack of seriousness", example: "The evening was full of lighthearted frivolity." },
  subscribed: { meaning: "signed up to receive something", example: "She subscribed to a cooking magazine." },
  handstand: { meaning: "balancing on your hands, feet up", example: "He held a handstand for ten seconds." },
  frequents: { meaning: "visits often", example: "He frequents the little café on the corner." },
  switcheroo: { meaning: "a surprise switch or swap", example: "They pulled a switcheroo with the boxes." },
  whittling: { meaning: "carving wood with a knife", example: "Grandpa is whittling a small bird." },
  rhinestones: { meaning: "sparkly imitation gems", example: "Her jacket was covered in rhinestones." },
  centralized: { meaning: "brought under one main control", example: "The school uses a centralized office." },
  machinations: { meaning: "secret plots and schemes", example: "The villain's machinations were exposed." },
  galvanized: { meaning: "shocked into action; coated with zinc", example: "The speech galvanized the crowd." },
  manganese: { meaning: "a gray metal element used in steel", example: "Manganese hardens the metal." },
  fragrances: { meaning: "pleasant smells", example: "The bakery's fragrances drifted outside." },
  mangroves: { meaning: "tropical trees that grow in water", example: "Mangroves shelter baby fish." },
  hippodrome: { meaning: "an arena for horse racing or shows", example: "The chariots circled the hippodrome." },
  flophouse: { meaning: "a cheap, rough place to sleep", example: "He stayed one night in a flophouse." },
  reprieved: { meaning: "excused from a punishment; given a break", example: "The prisoner was reprieved at the last moment." },
  apostolic: { meaning: "relating to the apostles or their faith", example: "The bishop holds apostolic authority." },
  guffawing: { meaning: "laughing loudly and coarsely", example: "The crowd was guffawing at the joke." },
  zoologist: { meaning: "a scientist who studies animals", example: "The zoologist studied the wolves." },
  pericardium: { meaning: "the sac around the heart", example: "Fluid had collected in the pericardium." },
  seaworthy: { meaning: "fit to sail the open sea", example: "The old boat was still seaworthy." },
  discusses: { meaning: "talks about with others", example: "The class discusses the novel together." },
  parentheses: { meaning: "curved marks ( ) used in writing", example: "Put the extra note in parentheses." },
  unconnected: { meaning: "not linked or related", example: "The two events seemed unconnected." },
  congeniality: { meaning: "a friendly, pleasant manner", example: "Her congeniality put everyone at ease." },
  potentials: { meaning: "hidden possibilities or abilities", example: "Two young athletes showed great potentials." },
  ventriloquism: { meaning: "speaking clearly without moving your lips", example: "Her act of ventriloquism amazed the kids." },
  shortbread: { meaning: "a crumbly, buttery cookie", example: "He dipped the shortbread in tea." },
  millimetres: { meaning: "tiny units of length (British spelling)", example: "The bolt is a few millimetres wide." },
  salacious: { meaning: "showing crude sexual interest", example: "The tabloid ran a salacious story." },
  backyards: { meaning: "the yards behind houses", example: "Kids played tag in the backyards." },
  daiquiris: { meaning: "rum drinks mixed with fruit", example: "They sipped frozen daiquiris by the pool." },
  antagonism: { meaning: "active dislike or hostility", example: "There was open antagonism between rivals." },
  copyrighted: { meaning: "legally protected as an author's work", example: "The song is copyrighted by the label." },
  inexorably: { meaning: "in a way that cannot be stopped", example: "The tide rose inexorably." },
  enslavement: { meaning: "the act of making someone a slave", example: "History tells of the enslavement of millions." },
  darwinism: { meaning: "the theory of evolution by natural selection", example: "The course covered Darwinism in depth." },
  inconsistency: { meaning: "a lack of sameness or reliability", example: "The player's inconsistency hurt the team." },
  emigrants: { meaning: "people who leave their country to live elsewhere", example: "The emigrants boarded the ship." },
  clenching: { meaning: "gripping tightly", example: "He was clenching his fists in anger." },
  hyperbole: { meaning: "extreme exaggeration for effect", example: "\"I waited forever\" is hyperbole." },
  heaviness: { meaning: "great weight; seriousness", example: "The heaviness of the box surprised me." },
  bookseller: { meaning: "a person who sells books", example: "The bookseller signed my copy." },
  frighteningly: { meaning: "in a scary way", example: "The storm grew frighteningly loud." },
  precipitate: { meaning: "to cause suddenly; to fall as rain", example: "Tension can precipitate an argument." },
  indeterminate: { meaning: "not fixed or known exactly", example: "The cause remained indeterminate." },
  marvelously: { meaning: "in a wonderful way", example: "The choir sang marvelously." },
  distancing: { meaning: "keeping apart", example: "The owl was distancing itself from us." },
  sainthood: { meaning: "the state of being a saint", example: "She was honored for a life of sainthood." },
  sugarplum: { meaning: "a piece of sugar candy", example: "The dream was of a dancing sugarplum." },
  forfeiture: { meaning: "loss of right or property as a penalty", example: "The court ordered forfeiture of the goods." },
  constancy: { meaning: "steady faithfulness; sameness", example: "The lighthouse was a symbol of constancy." },
  sequential: { meaning: "following an order one after another", example: "The steps must be done in sequential order." },
  acetylene: { meaning: "a gas used for welding", example: "The acetylene torch cut through steel." },
  liquidity: { meaning: "easy availability of cash or assets", example: "Banks must keep enough liquidity." },
  countered: { meaning: "opposed or answered back", example: "She countered with a stronger argument." },
  hypotenuse: { meaning: "the longest side of a right triangle", example: "Find the hypotenuse with the formula." },
  numbering: { meaning: "giving numbers in order", example: "Please keep the pages numbering correctly." },
  lubrication: { meaning: "the act of oiling to reduce friction", example: "Machines need regular lubrication." },
  industrialized: { meaning: "developed heavy industry", example: "The region industrialized in the 1900s." },
  mammogram: { meaning: "an X-ray of the breast", example: "She went in for a routine mammogram." },
  unshakable: { meaning: "firm; impossible to weaken", example: "Her faith was unshakable." },
  cessation: { meaning: "a stopping or ending", example: "They called for a cessation of fighting." },
  filaments: { meaning: "thin threads or wires", example: "The filaments glow inside the bulb." },
  respondent: { meaning: "a person who answers", example: "Each respondent filled out a form." },
  ceaseless: { meaning: "without stopping", example: "The ceaseless rain kept us inside." },
  deputized: { meaning: "given official power to act", example: "He was deputized to arrest the suspect." },
  memorials: { meaning: "things built to remember people or events", example: "War memorials stand in the square." },
  embittered: { meaning: "made bitter and resentful", example: "The unfair loss embittered the coach." },
  baseballs: { meaning: "the balls used in baseball games", example: "A bag of baseballs sat by the dugout." },
  convening: { meaning: "calling people together for a meeting", example: "The chair is convening the board." },
  appropriation: { meaning: "money set aside for a purpose; taking for one's own", example: "The appropriation funded new roads." },
  gyroscope: { meaning: "a spinning wheel used to keep balance", example: "The gyroscope keeps the ship steady." },
  prefrontal: { meaning: "at the front of the brain", example: "The prefrontal cortex guides decisions." },
  concussed: { meaning: "struck so as to injure the brain", example: "The player was concussed in the tackle." },
  locomotives: { meaning: "engines that pull trains", example: "Two locomotives pulled the long train." },
  balderdash: { meaning: "nonsense", example: "That excuse is sheer balderdash." },
  complying: { meaning: "obeying rules or requests", example: "Everyone is complying with the rules." },
  tactically: { meaning: "in a planned, strategic way", example: "They moved tactically across the field." },
  misconstrued: { meaning: "understood wrongly", example: "My joke was misconstrued as an insult." },
  inclinations: { meaning: "natural urges or leanings", example: "His inclinations led him to art." },
  footlocker: { meaning: "a chest for personal belongings", example: "He kept his gear in a footlocker." },
  backstabber: { meaning: "a person who betrays others secretly", example: "No one trusts a backstabber." },
  distributes: { meaning: "hands out; spreads around", example: "The teacher distributes the papers." },
  stargazer: { meaning: "a person who studies the stars", example: "The stargazer spotted a new comet." },
  exasperating: { meaning: "extremely annoying", example: "The slow traffic was exasperating." },
  calisthenics: { meaning: "exercises done without weights", example: "They began the day with calisthenics." },
  landslides: { meaning: "slides of earth down slopes; huge wins", example: "Heavy rain caused landslides." },
  interning: { meaning: "working as a student trainee", example: "She is interning at a law firm." },
  abstraction: { meaning: "a general idea not tied to one thing", example: "\"Freedom\" is an abstraction." },
  scrolling: { meaning: "moving text up or down a screen", example: "She kept scrolling through the news." },
  ruination: { meaning: "total destruction", example: "The flood spelled ruination for the crops." },
  bootleggers: { meaning: "people who smuggle goods", example: "Bootleggers hid the cases in the cellar." },
  disapproves: { meaning: "regards something as wrong", example: "She disapproves of rude talk." },
  legitimize: { meaning: "to make legal or acceptable", example: "The vote helped legitimize the new policy." },
  disembarked: { meaning: "got off a ship or plane", example: "Passengers disembarked onto the dock." },
  entertainments: { meaning: "shows and activities for fun", example: "The festival offered many entertainments." },
  jubilation: { meaning: "great joy and celebration", example: "The crowd cheered in jubilation." },
  symphonies: { meaning: "long pieces of orchestral music", example: "She composed two symphonies." },
  turnstile: { meaning: "a gate that lets people through one by one", example: "Swipe your card at the turnstile." },
  convicting: { meaning: "proving someone guilty", example: "The evidence led to convicting the thief." },
  strikingly: { meaning: "in a very noticeable way", example: "The twins look strikingly alike." },
  supernovas: { meaning: "exploding stars", example: "Telescopes record distant supernovas." },
  stranglehold: { meaning: "a grip or control that prevents movement", example: "The cartel held a stranglehold on trade." },
  stepladder: { meaning: "a small folding ladder", example: "He reached the shelf with a stepladder." },
  rechecked: { meaning: "checked again", example: "She rechecked her answers twice." },
  elevating: { meaning: "raising to a higher level", example: "They are elevating the platform slowly." },
  testimonials: { meaning: "statements praising someone or something", example: "The ad was full of customer testimonials." },
  talismans: { meaning: "objects believed to bring luck", example: "She carried tiny talismans for luck." },
  seasickness: { meaning: "nausea caused by riding on the sea", example: "He took medicine for seasickness." },
  proctologist: { meaning: "a doctor of the lower digestive tract", example: "The proctologist reviewed the scan." },
  extractor: { meaning: "a device that pulls something out", example: "The extractor holds the juice." },
  mitigation: { meaning: "making something less severe", example: "Trees help in the mitigation of floods." },
  inhibition: { meaning: "a feeling that holds you back", example: "She lost her inhibition on stage." },
  wholesalers: { meaning: "businesses that sell goods in bulk", example: "Wholesalers supply many small shops." },
  optimization: { meaning: "making something as good as possible", example: "The team focused on speed optimization." },
  parachuting: { meaning: "jumping from a plane with a parachute", example: "Parachuting is a thrilling sport." },
  rorschach: { meaning: "a test using inkblot images", example: "The rorschach test shows how you see." },
  implicates: { meaning: "shows someone to be involved", example: "The note implicates her in the prank." },
  noteworthy: { meaning: "worth noticing; important", example: "The victory was noteworthy for the team." },
  reformers: { meaning: "people who push for change", example: "Social reformers fought for new laws." },
  intendant: { meaning: "a manager or administrator", example: "The intendant oversaw the estate." },
  vaccinate: { meaning: "to protect by giving a vaccine", example: "Doctors vaccinate children each fall." },
  lipsticks: { meaning: "sticks of colored makeup for lips", example: "She owns a bright red lipsticks." },
  tracheotomy: { meaning: "a cut made to open the windpipe", example: "The surgeon performed a tracheotomy." },
  blackballed: { meaning: "excluded from a group by a secret vote", example: "They blackballed him from the club." },
  untalented: { meaning: "lacking special ability", example: "He felt untalented at painting." },
  freshening: { meaning: "making fresh or cleaner", example: "The wind is freshening the air." },
  subjugate: { meaning: "to bring under control; conquer", example: "The army moved to subjugate the region." },
  yesteryear: { meaning: "the past; former times", example: "Those fashions belong to yesteryear." },
  joyriding: { meaning: "stealing a car for a thrill ride", example: "They were caught joyriding downtown." },
  colorblind: { meaning: "unable to see some colors", example: "He is colorblind and can't see red." },
  kalashnikov: { meaning: "a type of automatic rifle", example: "The guard carried a kalashnikov." },
  calamities: { meaning: "terrible disasters", example: "Floods are among nature's calamities." },
  intricacies: { meaning: "fine, complicated details", example: "The plan's intricacies took hours to learn." },
  workspace: { meaning: "the area where someone works", example: "Her workspace is neat and bright." },
  watermark: { meaning: "a faint design pressed into paper", example: "The money has a hidden watermark." },
  slouching: { meaning: "sitting or standing with a droop", example: "Stop slouching at the table." },
  shapeless: { meaning: "without a clear shape", example: "The old coat hung shapeless on him." },
  orchestrating: { meaning: "arranging music; planning carefully", example: "She is orchestrating the whole event." },
  cloistered: { meaning: "kept away from the outside world", example: "The monks led a cloistered life." },
  semiautomatic: { meaning: "firing one bullet per trigger pull", example: "The weapon was semiautomatic." },
  contortionist: { meaning: "a performer who twists the body", example: "The contortionist folded into a box." },
  eliminations: { meaning: "removals from a contest", example: "The eliminations left six contestants." },
  suppository: { meaning: "medicine placed in the body cavity", example: "The nurse gave him a suppository." },
  revisiting: { meaning: "visiting or considering again", example: "We are revisiting the old route." },
  painlessly: { meaning: "without pain", example: "The dentist removed it painlessly." },
  incalculable: { meaning: "too great to be counted", example: "The damage was incalculable." },
  stratagem: { meaning: "a clever plan or trick", example: "His stratagem fooled the guards." },
  chopstick: { meaning: "a slim stick used to eat with", example: "He lifted the rice with one chopstick." },
  refurbished: { meaning: "restored and cleaned", example: "They sold refurbished laptops." },
  gangplank: { meaning: "a ramp to board a ship", example: "The sailors rolled out the gangplank." },
  meditative: { meaning: "calm and thoughtful", example: "She sat in a meditative pose." },
  overrides: { meaning: "takes control over something else", example: "The big button overrides all settings." },
  belittling: { meaning: "making someone seem small or unimportant", example: "He kept belittling her efforts." },
  reintroduce: { meaning: "to bring back into use", example: "They hope to reintroduce the old tradition." },
  countermeasure: { meaning: "an action taken to oppose another", example: "The shield is a countermeasure to rockets." },
  aftershock: { meaning: "a smaller quake after the main one", example: "An aftershock rattled the town." },
  coefficient: { meaning: "a number that multiplies a variable", example: "In 3x, three is the coefficient." },
  osteoporosis: { meaning: "a disease that makes bones brittle", example: "Calcium helps prevent osteoporosis." },
  felonious: { meaning: "related to a serious crime", example: "He was charged with a felonious act." },
  sharpness: { meaning: "the quality of being sharp", example: "The knife's sharpness amazed me." },
  resuscitated: { meaning: "brought back to consciousness", example: "They resuscitated the swimmer." },
  rebellions: { meaning: "armed uprisings against rulers", example: "History records two great rebellions." },
  facilitator: { meaning: "a person who helps a group work well", example: "The facilitator kept the meeting on time." },
  concerted: { meaning: "done together in a strong effort", example: "A concerted effort cleaned the park." },
  scarecrows: { meaning: "figures set up to scare birds", example: "Scarecrows stand in the cornfields." },
  ectoplasm: { meaning: "a ghostly substance (in some beliefs)", example: "The movie showed a wispy ectoplasm." },
  recruiters: { meaning: "people who find new members or workers", example: "Army recruiters visited the school." },
  storytellers: { meaning: "people who tell stories", example: "Campfire storytellers kept us spellbound." },
  sheepskin: { meaning: "the skin of a sheep with its wool", example: "A warm sheepskin lined the boots." },
  depositors: { meaning: "people who put money in a bank", example: "The bank reassured its depositors." },
  herbalist: { meaning: "a person skilled with healing plants", example: "The herbalist mixed a tea for coughs." },
  unequivocal: { meaning: "clear and definite", example: "Her answer was a firm, unequivocal yes." },
  scapegoats: { meaning: "people unfairly blamed for others' faults", example: "Two interns became the scapegoats." },
  sesterces: { meaning: "ancient Roman coins", example: "The museum shows a jar of sesterces." },
  interacts: { meaning: "acts with or affects something else", example: "The new drug interacts with coffee." },
  obediently: { meaning: "in a way that follows orders", example: "The dog sat obediently at his side." },
  interposing: { meaning: "placing between; cutting in", example: "He kept interposing in the debate." },
  disassembled: { meaning: "taken apart piece by piece", example: "We disassembled the clock to clean it." },
  differing: { meaning: "being different", example: "The twins have differing tastes." },
  impeccably: { meaning: "perfectly; without flaw", example: "The suite was impeccably clean." },
  incapacitate: { meaning: "to make unable to act", example: "A sprain can incapacitate a runner." },
  sacrosanct: { meaning: "too sacred to be changed", example: "The tradition was sacrosanct to the family." },
  misconceptions: { meaning: "wrong beliefs or ideas", example: "The guide cleared up common misconceptions." },
  heatstroke: { meaning: "illness from too much heat", example: "Drink water to avoid heatstroke." },
  inopportune: { meaning: "badly timed; inconvenient", example: "The call came at an inopportune moment." },
  degenerated: { meaning: "became worse or lower", example: "The argument degenerated into a shout." },
  beefsteak: { meaning: "a thick slice of beef", example: "He grilled a beefsteak for dinner." },
  reposition: { meaning: "to move to a new place", example: "Please reposition the lamp." },
  deepening: { meaning: "growing deeper", example: "The deepening river frightened us." },
  moonbeams: { meaning: "rays of moonlight", example: "Moonbeams lit the quiet lake." },
  nanosecond: { meaning: "one billionth of a second", example: "The chip switches in a nanosecond." },
  inexorable: { meaning: "impossible to stop", example: "Time moves on, inexorable." },
  persevered: { meaning: "kept going through difficulty", example: "She persevered and finished the race." },
  paraphrase: { meaning: "to restate in other words", example: "Paraphrase the quote in your own words." },
  uninformed: { meaning: "not knowing the facts", example: "He made an uninformed guess." },
  microcosm: { meaning: "a small world that shows a larger one", example: "The town is a microcosm of the country." },
  dramamine: { meaning: "medicine for motion sickness", example: "She took dramamine before the boat ride." },
  inspirations: { meaning: "things that spark creativity", example: "Nature is one of her inspirations." },
  tamponade: { meaning: "fluid pressure on the heart", example: "Cardiac tamponade needs fast care." },
  immutable: { meaning: "impossible to change", example: "The law of gravity is immutable." },
  appeasement: { meaning: "calming an aggressor by giving in", example: "History warns against appeasement." },
  quicksilver: { meaning: "an old name for mercury; lively", example: "He moved like quicksilver." },
  annexation: { meaning: "taking over and adding territory", example: "The annexation of the land was disputed." },
  bathwater: { meaning: "the water in a bath", example: "Don't throw out the bathwater yet." },
  overbooked: { meaning: "sold more seats than available", example: "The flight was overbooked." },
  liverwurst: { meaning: "a liver-flavored sausage", example: "He spread liverwurst on bread." },
  immensity: { meaning: "a huge, vast size", example: "The immensity of space humbles us." },
  modulator: { meaning: "a device that changes a signal", example: "The modulator adjusts the waves." },
  ferociously: { meaning: "fercely; wildly", example: "The dog guarded the yard ferociously." },
  broadside: { meaning: "a strong attack; the side of a ship", example: "The fleet fired a broadside." },
  doubloons: { meaning: "old Spanish gold coins", example: "Pirates buried their doubloons." },
  modernize: { meaning: "to bring up to date", example: "The city plans to modernize the trains." },
  dilettante: { meaning: "a person who dabbles without deep skill", example: "He was a dilettante at painting." },
  halitosis: { meaning: "bad breath", example: "Mint gums help prevent halitosis." },
  perishing: { meaning: "dying; very cold", example: "The lost hikers were perishing." },
  ransacking: { meaning: "searching and turning over roughly", example: "They were ransacking the drawers." },
  womanizing: { meaning: "pursuing romantic conquests casually", example: "His womanizing made headlines." },
  libertarian: { meaning: "one who values personal freedom highly", example: "A libertarian favors small government." },
  duplicity: { meaning: "deceit; double-dealing", example: "His duplicity ended the friendship." },
  fossilised: { meaning: "turned into fossil (British spelling)", example: "The ammonite was fossilised in stone." },
  inextricably: { meaning: "in a way that can't be separated", example: "The two histories are inextricably linked." },
  indentations: { meaning: "dents or notches", example: "The soft clay held deep indentations." },
  optometrist: { meaning: "a doctor who tests eyesight", example: "The optometrist prescribed new glasses." },
  centurions: { meaning: "officers in an ancient Roman army", example: "The centurions led the ranks." },
  immobilize: { meaning: "to make unable to move", example: "A cast will immobilize the arm." },
  biosphere: { meaning: "all the areas where life exists on Earth", example: "The biosphere holds every living thing." },
  businesslike: { meaning: "efficient and serious", example: "Her businesslike manner got results." },
  castellan: { meaning: "the keeper of a castle", example: "The castellan opened the great gate." },
  enriching: { meaning: "making richer or better", example: "Reading is an enriching habit." },
  ambushing: { meaning: "attacking from a hidden place", example: "They were ambushing the convoy." },
  desiccated: { meaning: "dried out completely", example: "Desiccated coconut keeps for months." },
  westerner: { meaning: "a person from the West", example: "The westerner toured the temple." },
  carburettor: { meaning: "a device that mixes fuel and air (British spelling)", example: "The mechanic cleaned the carburettor." },
  conscripted: { meaning: "forced into military service", example: "Young men were conscripted in the war." },
  prearranged: { meaning: "planned ahead of time", example: "Their meeting was prearranged." },
  homeopathic: { meaning: "related to a gentle natural medicine", example: "She tried homeopathic remedies." },
  pictorial: { meaning: "relating to or shown in pictures", example: "The book is a pictorial history." },
  schizophrenics: { meaning: "people with a severe mental illness", example: "The clinic supports patients called schizophrenics." },
  paparazzo: { meaning: "a photographer who chases celebrities", example: "A paparazzo snapped the singer." },
  multiplex: { meaning: "a cinema with many screens", example: "The multiplex shows six films at once." },
  chairperson: { meaning: "the leader of a meeting or board", example: "The chairperson called for order." },
  fingertip: { meaning: "the tip of a finger", example: "The ball grazed his fingertip." },
  tenements: { meaning: "poorly built apartments in a city", example: "The old tenements were torn down." },
  copacetic: { meaning: "fine; completely okay", example: "Everything is copacetic now." },
  concretely: { meaning: "in a real, specific way", example: "Let's plan concretely, not vaguely." },
  horseplay: { meaning: "rough, silly play", example: "No horseplay near the pool." },
  contraptions: { meaning: "odd, clever devices", example: "The shed was full of contraptions." },
  cauterize: { meaning: "to burn a wound to seal it", example: "The medic moved to cauterize the cut." },
  weightlessness: { meaning: "the state of having no weight", example: "Astronauts enjoy weightlessness in orbit." },
  crustaceans: { meaning: "animals with shells like crabs and lobsters", example: "Crustaceans live along the coast." },
  theologian: { meaning: "a scholar of religion and God", example: "The theologian wrote about faith." },
  conveyance: { meaning: "a vehicle; the act of carrying", example: "The carriage was a fine conveyance." },
  jurisdictional: { meaning: "related to legal authority", example: "The court had jurisdictional power." },
  overstating: { meaning: "saying too much; exaggerating", example: "He is overstating the danger." },
  antihistamine: { meaning: "a medicine for allergies", example: "An antihistamine calmed her sneezing." },
  stipulates: { meaning: "demands as a condition", example: "The contract stipulates a deadline." },
  restorative: { meaning: "something that restores strength", example: "The nap was restorative." },
  jumpsuits: { meaning: "one-piece outfits covering the body", example: "The pilots wore orange jumpsuits." },
  infiltrators: { meaning: "people who slip into a group secretly", example: "Guards stopped the infiltrators." },
  compatriot: { meaning: "a person from the same country", example: "He was glad to meet a compatriot." },
  overblown: { meaning: "made to seem bigger than real", example: "The media coverage was overblown." },
  exterminators: { meaning: "people hired to kill pests", example: "Exterminators rid the house of termites." },
  breastplate: { meaning: "armor covering the chest", example: "His breastplate gleamed in the sun." },
  practicality: { meaning: "the quality of being workable", example: "Consider the practicality of the plan." },
  teleporting: { meaning: "moving instantly across space (in fiction)", example: "The hero is teleporting across worlds." },
  newfangled: { meaning: "new and unfamiliar (often suspiciously so)", example: "He distrusts newfangled gadgets." },
  superheated: { meaning: "heated to a very high temperature", example: "The superheated steel glowed orange." },
  unfashionable: { meaning: "not in style", example: "Wide ties became unfashionable." },
  dissonance: { meaning: "a clash of sounds or ideas", example: "The two chords created dissonance." },
  pilfering: { meaning: "stealing small things", example: "He was caught pilfering pens." },
  saddlebags: { meaning: "bags hung over a saddle", example: "The rider packed the saddlebags." },
  eligibility: { meaning: "the state of being qualified", example: "Age determines eligibility to vote." },
  socialise: { meaning: "to mix with others (British spelling)", example: "They socialise after work." },
  padlocked: { meaning: "locked with a padlock", example: "The gate was padlocked shut." },
  beleaguered: { meaning: "under constant pressure or attack", example: "The beleaguered town held out." },
  storekeeper: { meaning: "the owner or keeper of a store", example: "The storekeeper weighed the grain." },
  accommodated: { meaning: "provided room or fit in with", example: "The inn accommodated fifty guests." },
  crustacean: { meaning: "an animal with a shell like a crab", example: "A lobster is a large crustacean." },
  hairpiece: { meaning: "a wig for part of the head", example: "He wore a hairpiece for the role." },
  personage: { meaning: "an important person", example: "A royal personage visited the town." },
  innovators: { meaning: "people who introduce new ideas", example: "Tech innovators changed daily life." },
  dampening: { meaning: "making slightly wet; lessening", example: "Rain is dampening the parade." },
  catharsis: { meaning: "a release of strong emotion", example: "Tears brought her a sense of catharsis." },
  aqueducts: { meaning: "bridges that carry water", example: "Ancient aqueducts fed the city." },
  dignitary: { meaning: "a person of high rank", example: "A foreign dignitary gave a speech." },
  bedsheets: { meaning: "the cloth covers for a bed", example: "Fresh bedsheets smell wonderful." },
  patrolmen: { meaning: "police officers who patrol", example: "Two patrolmen walked the street." },
  interpreters: { meaning: "people who translate speech", example: "The interpreters worked in pairs." },
  exorcisms: { meaning: "ceremonies to drive out evil spirits", example: "The film told of old exorcisms." },
  jurisprudence: { meaning: "the science of law", example: "She studies jurisprudence in college." },
  chickpeas: { meaning: "round beans also called garbanzos", example: "Hummus is made from chickpeas." },
  xylophone: { meaning: "a musical instrument with wooden bars", example: "He plays the xylophone in band." },
  irrationally: { meaning: "in a way not based on reason", example: "He acted irrationally in panic." },
  irritability: { meaning: "a tendency to get annoyed easily", example: "Lack of sleep causes irritability." },
  projectors: { meaning: "devices that throw images on a screen", example: "Old projectors showed film reels." },
  scratcher: { meaning: "a tool or animal that scratches", example: "I bought a lottery scratcher." },
  staircases: { meaning: "sets of stairs", example: "Two staircases lead to the attic." },
  demeanour: { meaning: "the way a person appears and behaves", example: "Her calm demeanour calmed us." },
  uneasiness: { meaning: "an anxious, uncomfortable feeling", example: "A quiet uneasiness filled the room." },
  safecracker: { meaning: "a person who opens safes illegally", example: "The safecracker heard the lock click." },
  shanghaied: { meaning: "forced to join a ship's crew; tricked", example: "Sailors feared being shanghaied." },
  outpouring: { meaning: "a strong, flowing release", example: "An outpouring of love followed." },
  trumpeter: { meaning: "a person who plays the trumpet", example: "The trumpeter played a solo." },
  independents: { meaning: "people not tied to a group or party", example: "The election drew many independents." },
  borrowers: { meaning: "people who take money or things to return", example: "The library fines late borrowers." },
  thunderbolts: { meaning: "flashes of lightning with thunder", example: "Thunderbolts split the night sky." },
  communique: { meaning: "an official announcement", example: "The leaders issued a communique." },
  touchstone: { meaning: "a standard used to judge things", example: "The test became the touchstone of quality." },
  headstones: { meaning: "stone markers on graves", example: "Old headstones lean in the churchyard." },
  redefined: { meaning: "gave a new meaning to", example: "The discovery redefined the field." },
  alarmingly: { meaning: "in a worrying way", example: "Prices rose alarmingly fast." },
  culminated: { meaning: "reached the highest point", example: "The season culminated in a win." },
  cornucopia: { meaning: "a plentiful, abundant supply", example: "The market is a cornucopia of fruit." },
  bloodletting: { meaning: "deliberate injury or killing", example: "The war led to terrible bloodletting." },
  conquistador: { meaning: "a Spanish conqueror of the Americas", example: "The conquistador claimed the land." },
  taskmaster: { meaning: "a strict person who demands hard work", example: "The boss is a tough taskmaster." },
  chronically: { meaning: "continuing for a long time", example: "He suffers from chronically sore knees." },
  overflowed: { meaning: "ran over the top", example: "The sink overflowed onto the floor." },
  physicality: { meaning: "the quality of being physical", example: "Dance celebrates the human physicality." },
  oligarchs: { meaning: "a few wealthy rulers of a country", example: "The oligarchs controlled the industry." },
  dishonorably: { meaning: "in a shameful way", example: "He left the post dishonorably." },
  interloper: { meaning: "an intruder; an uninvited person", example: "An interloper crashed the meeting." },
  pericardial: { meaning: "relating to the sac around the heart", example: "Pericardial pain sent her to the doctor." },
};