// Medium-tier vocab hints for Spell It — loaded BEFORE script.js.
// Mirrors the medium tier of words.js. Each entry: meaning + example sentence.
const MEDIUM_DEFS = {
  determine: { meaning: "to find out or decide", example: "We need to determine the exact time." },
  terrorists: { meaning: "people who use fear and violence", example: "The town stood strong against terrorists." },
  elsewhere: { meaning: "in or to another place", example: "The key must be elsewhere." },
  practical: { meaning: "useful and sensible", example: "Ropes and clips are practical tools." },
  adorable: { meaning: "very cute and lovable", example: "The kitten in the window is adorable." },
  operating: { meaning: "running or working a machine", example: "She is operating the new forklift." },
  apologies: { meaning: "words said when sorry", example: "He offered his apologies for being late." },
  personnel: { meaning: "the people who work somewhere", example: "All personnel must wear a badge." },
  samples: { meaning: "small examples of something", example: "The store gave out free samples." },
  counselor: { meaning: "someone who advises or guides", example: "The camp counselor taught us a song." },
  floating: { meaning: "resting on the surface of liquid", example: "Leaves were floating on the pond." },
  journalist: { meaning: "a person who writes news", example: "The journalist interviewed the mayor." },
  operator: { meaning: "someone who runs a machine", example: "The elevator operator closed the doors." },
  arrives: { meaning: "reaches a place", example: "The train arrives at noon." },
  eastern: { meaning: "of or toward the east", example: "The sun rises in the eastern sky." },
  remaining: { meaning: "still left over", example: "The remaining cookies are in the jar." },
  december: { meaning: "the last month of the year", example: "December brings snow and holidays." },
  anonymous: { meaning: "with the name unknown", example: "The note was written anonymously." },
  reporting: { meaning: "giving news or information", example: "She is reporting on the big game." },
  islands: { meaning: "lands surrounded by water", example: "The islands are home to many birds." },
  roommate: { meaning: "a person who shares a room", example: "Her roommate wakes up early." },
  visitor: { meaning: "a person who comes to see a place", example: "A visitor asked for directions." },
  giggling: { meaning: "laughing in a light, silly way", example: "The friends were giggling at the joke." },
  commitment: { meaning: "a promise or dedication", example: "She showed real commitment to practice." },
  protest: { meaning: "to speak out against something", example: "The workers protested the changes." },
  embrace: { meaning: "to hug, or to accept gladly", example: "They embraced the new idea." },
  fathers: { meaning: "male parents", example: "The fathers coached the team." },
  faithful: { meaning: "loyal and constant", example: "The faithful dog waited by the door." },
  cemetery: { meaning: "a place where the dead are buried", example: "Old oaks line the small cemetery." },
  emotion: { meaning: "a strong feeling", example: "Joy is a wonderful emotion." },
  excuses: { meaning: "reasons given for not doing something", example: "Stop making excuses and try." },
  efforts: { meaning: "times of hard work", example: "Her efforts made the party perfect." },
  content: { meaning: "happy and satisfied", example: "The cat was content in the sun." },
  corporal: { meaning: "of the body; a military rank", example: "The corporal gave the command." },
  hopeless: { meaning: "without hope", example: "The case seemed hopeless." },
  luckily: { meaning: "by good fortune", example: "Luckily, the rain stopped." },
  profession: { meaning: "a job that needs training", example: "Teaching is a caring profession." },
  symptoms: { meaning: "signs of an illness", example: "A cough is one symptom of a cold." },
  aircraft: { meaning: "machines that fly", example: "The aircraft circled the airport." },
  aggressive: { meaning: "rough, forceful, or bold", example: "The aggressive dog barked loudly." },
  embassy: { meaning: "a country's offices in another land", example: "They applied for a visa at the embassy." },
  defence: { meaning: "protection against attack", example: "The wall was their defence." },
  cabinet: { meaning: "a storage cupboard; advisors", example: "The dishes are in the cabinet." },
  display: { meaning: "to show; a visual show", example: "The store will display the new toys." },
  filming: { meaning: "recording with a camera", example: "They are filming a movie downtown." },
  penalty: { meaning: "a punishment, as in a game", example: "The foul cost the team a penalty." },
  bargain: { meaning: "a great deal; to haggle", example: "That jacket was a bargain." },
  speaker: { meaning: "one who talks; a sound device", example: "The speaker's voice filled the room." },
  compare: { meaning: "to look at how things differ", example: "Compare the two pictures carefully." },
  envelope: { meaning: "a paper cover for a letter", example: "She sealed the envelope." },
  african: { meaning: "from the continent of Africa", example: "The African drum had a deep beat." },
  believing: { meaning: "trusting that something is true", example: "Believing in yourself helps you succeed." },
  attacking: { meaning: "moving against with force", example: "The bees attacked the intruder." },
  storage: { meaning: "a place for keeping things", example: "Boxes fill the storage room." },
  climbing: { meaning: "moving upward using hands and feet", example: "They are climbing the tall hill." },
  corporate: { meaning: "relating to large companies", example: "He works in the corporate office." },
  smarter: { meaning: "more intelligent", example: "Practice makes you smarter." },
  surprising: { meaning: "causing wonder or surprise", example: "The ending of the book is surprising." },
  primary: { meaning: "most important; first", example: "Safety is our primary concern." },
  motorcycle: { meaning: "a two-wheeled motor vehicle", example: "The motorcycle zoomed past us." },
  planets: { meaning: "large bodies that orbit a star", example: "Jupiter is one of the planets." },
  surprises: { meaning: "things that happen unexpectedly", example: "Life is full of surprises." },
  trailer: { meaning: "a wheeled home or cargo box", example: "They towed the trailer to the lake." },
  teenage: { meaning: "ages thirteen through nineteen", example: "Her teenage brother loves music." },
  cooperate: { meaning: "to work well together", example: "We cooperate to finish chores." },
  worthless: { meaning: "having no value", example: "The broken toy was worthless." },
  arriving: { meaning: "reaching a destination", example: "Help is arriving soon." },
  kindness: { meaning: "the quality of being kind", example: "Kindness costs nothing." },
  relations: { meaning: "connections or family members", example: "The two teams have good relations." },
  perfume: { meaning: "a sweet-smelling liquid", example: "She wore a lovely perfume." },
  january: { meaning: "the first month of the year", example: "January begins the new year." },
  gallery: { meaning: "a room for showing art", example: "The gallery hangs modern paintings." },
  activities: { meaning: "things people do", example: "Camp offers many fun activities." },
  boarding: { meaning: "getting onto a craft; a school with rooms", example: "Boarding the plane took a while." },
  improve: { meaning: "to make better", example: "Reading daily will improve your spelling." },
  creation: { meaning: "something made; the act of making", example: "This cake is a creation of my mom." },
  infection: { meaning: "an illness caused by germs", example: "Wash cuts to avoid infection." },
  strikes: { meaning: "hits; stops work; finds suddenly", example: "Lightning strikes the tall tree." },
  tension: { meaning: "tightness or strain", example: "There was tension before the test." },
  whistles: { meaning: "clear high sounds", example: "The referee's whistles stop the game." },
  threats: { meaning: "warnings of danger or harm", example: "The wolf ignored the threats." },
  martial: { meaning: "relating to war or fighting", example: "He practices martial arts." },
  imperial: { meaning: "relating to an empire or ruler", example: "The imperial palace is grand." },
  paranoid: { meaning: "wildly suspicious of others", example: "Loud noises made him paranoid." },
  signing: { meaning: "writing your name; using signs", example: "She is signing the papers now." },
  congress: { meaning: "a nation's law-making body", example: "Congress passed a new law." },
  candles: { meaning: "wax sticks with wicks that burn", example: "The birthday candles were lit." },
  filling: { meaning: "making full; a tooth repair; inside filling", example: "The pie has a sweet filling." },
  recovery: { meaning: "returning to good health", example: "Rest helps your recovery." },
  volunteer: { meaning: "one who helps without pay; to offer", example: "She is a volunteer at the shelter." },
  positions: { meaning: "places; jobs; ways of standing", example: "We moved to our positions on the field." },
  observe: { meaning: "to watch carefully", example: "Observe the frog before it jumps." },
  psychic: { meaning: "claiming to sense the unseen", example: "He visited a psychic for fun." },
  handling: { meaning: "dealing with; touching", example: "She is handling the phone calls." },
  conclusion: { meaning: "the final result or ending", example: "The story reached a happy conclusion." },
  designer: { meaning: "a person who creates designs", example: "The designer sketched a new dress." },
  importance: { meaning: "the state of being important", example: "Sleep is of great importance." },
  destroying: { meaning: "ruining completely", example: "The fire was destroying the barn." },
  communist: { meaning: "relating to communism", example: "The book describes the communist movement." },
  blackmail: { meaning: "demanding money by threats", example: "He tried to blackmail the owner." },
  pacific: { meaning: "peaceful; the large ocean", example: "The Pacific Ocean is vast." },
  glorious: { meaning: "splendid and wonderful", example: "The sunset was glorious." },
  fooling: { meaning: "tricking or joking", example: "Are you fooling me?" },
  persons: { meaning: "formal word for people", example: "Two persons were seen nearby." },
  addition: { meaning: "adding; something added", example: "Addition is an easy skill to learn." },
  graduate: { meaning: "to finish studies; a finishing student", example: "She will graduate in May." },
  anyways: { meaning: "in any case (informal)", example: "Anyways, let's get going." },
  genuine: { meaning: "real and honest", example: "Her smile was genuine." },
  judging: { meaning: "deciding or forming an opinion", example: "Judging by the smoke, lunch is ready." },
  ceiling: { meaning: "the top surface of a room", example: "A fan hung from the ceiling." },
  practicing: { meaning: "doing something again to improve", example: "She is practicing the piano." },
  somewhat: { meaning: "to some degree; a little", example: "I am somewhat tired." },
  gathering: { meaning: "a meeting; collecting together", example: "A gathering of friends filled the yard." },
  warriors: { meaning: "brave fighting people", example: "The warriors marched to battle." },
  electrical: { meaning: "related to or powered by electricity", example: "The electrical wire was repaired." },
  couples: { meaning: "pairs, often of partners", example: "Three couples danced together." },
  institute: { meaning: "an organization for study or work", example: "The institute studies ocean life." },
  principle: { meaning: "a basic rule or belief", example: "Honesty is a guiding principle." },
  therapist: { meaning: "a health professional who treats", example: "The therapist helped him heal." },
  compete: { meaning: "to take part in a contest", example: "They compete in the spelling bee." },
  compliment: { meaning: "a kind word; to praise", example: "She gave me a nice compliment." },
  worship: { meaning: "to show deep respect, often to a god", example: "They worship at the temple." },
  residence: { meaning: "a home or dwelling", example: "The governor has an official residence." },
  democracy: { meaning: "government by the people", example: "In a democracy, citizens vote." },
  helpless: { meaning: "unable to help yourself", example: "The fish was helpless out of water." },
  execution: { meaning: "a legal killing; putting a plan into action", example: "The plan was carried to execution." },
  appetite: { meaning: "desire for food", example: "Swimming gives me an appetite." },
  strictly: { meaning: "in a firm, exact way", example: "The rules are strictly followed." },
  chickens: { meaning: "farm birds that lay eggs", example: "The chickens pecked at their corn." },
  technical: { meaning: "relating to science or machines", example: "The manual is full of technical words." },
  shepherd: { meaning: "a person who tends sheep", example: "The shepherd led the flock home." },
  dresses: { meaning: "one-piece garments; clothes someone", example: "She dresses warmly in winter." },
  overcome: { meaning: "to defeat or get past", example: "She overcame her fear of dogs." },
  suggestion: { meaning: "an idea offered to others", example: "Thanks for your suggestion." },
  formula: { meaning: "a set of letters and numbers in math or science", example: "We used a formula to solve it." },
  samurai: { meaning: "a Japanese warrior", example: "The samurai carried a curved sword." },
  wandering: { meaning: "roaming without a fixed path", example: "He is wandering through the forest." },
  butcher: { meaning: "one who cuts and sells meat", example: "The butcher weighed the beef." },
  ministry: { meaning: "a government department; clergy work", example: "She works for the health ministry." },
  sweater: { meaning: "a warm knitted top", example: "He wore a thick sweater." },
  apologise: { meaning: "to say sorry (British spelling)", example: "I apologise for the noise." },
  examine: { meaning: "to look at closely", example: "The vet will examine the cat." },
  passage: { meaning: "a section of text; a way through", example: "Read the second passage aloud." },
  reaching: { meaning: "stretching toward; arriving at", example: "She is reaching for the top shelf." },
  directions: { meaning: "instructions on how to go", example: "The map gave clear directions." },
  strings: { meaning: "thin cords; things on instruments", example: "The guitar has six strings." },
  element: { meaning: "a basic substance or part", example: "Oxygen is an important element." },
  balloon: { meaning: "a colorful air-filled bag", example: "The balloon floated up high." },
  broadcast: { meaning: "to send out on radio or TV", example: "The station will broadcast the game." },
  eternity: { meaning: "time without end", example: "Waiting felt like an eternity." },
  nations: { meaning: "countries; groups of people", example: "Many nations joined the talks." },
  behaviour: { meaning: "the way someone acts", example: "His behaviour improved in class." },
  concrete: { meaning: "real and specific; building material", example: "A concrete wall surrounds the lot." },
  vegetables: { meaning: "plants grown for food", example: "Carrots are crunchy vegetables." },
  sausage: { meaning: "ground meat in a casing", example: "He grilled a sausage for lunch." },
  constable: { meaning: "a police officer (British use)", example: "The constable walked his beat." },
  spinning: { meaning: "turning around quickly", example: "The top is spinning on the floor." },
  genetic: { meaning: "relating to genes", example: "Eye color is genetic." },
  marvelous: { meaning: "wonderful; amazing", example: "The view from the hill is marvelous." },
  protocol: { meaning: "a set of rules or steps", example: "The scientist followed the protocol." },
  muscles: { meaning: "body parts that move bones", example: "Running builds strong muscles." },
  finishing: { meaning: "completing the last part", example: "He is finishing his homework." },
  products: { meaning: "things that are made or sold", example: "The store sells dairy products." },
  invasion: { meaning: "entering by force", example: "The army led an invasion." },
  affection: { meaning: "a feeling of fondness", example: "She showed affection to the puppy." },
  endless: { meaning: "having no end", example: "The desert seemed endless." },
  discipline: { meaning: "training of self-control", example: "Practice takes discipline." },
  absence: { meaning: "the state of being away", example: "His absence was noticed at practice." },
  philosophy: { meaning: "the study of wisdom and ideas", example: "She reads about philosophy." },
  verdict: { meaning: "a decision, as by a jury", example: "The jury reached a verdict." },
  privilege: { meaning: "a special right or advantage", example: "It is a privilege to be captain." },
  daylight: { meaning: "the light of day", example: "The daylight filled the room." },
  controls: { meaning: "buttons that run a machine; manages", example: "The pilot used the controls." },
  airplane: { meaning: "a powered flying vehicle", example: "The airplane landed smoothly." },
  blaring: { meaning: "making a loud, harsh sound", example: "The horn was blaring all night." },
  consent: { meaning: "permission to do something", example: "We have your consent to continue." },
  disagree: { meaning: "to have a different opinion", example: "I disagree with that idea." },
  celebrity: { meaning: "a famous person", example: "The celebrity waved at the crowd." },
  sniffles: { meaning: "slight cold with sniffling", example: "She has the sniffles today." },
  intentions: { meaning: "plans or aims", example: "His intentions were sincere." },
  farmers: { meaning: "people who grow crops or raise animals", example: "The farmers harvest the wheat." },
  convenient: { meaning: "easy and suited to your needs", example: "A corner store is convenient." },
  instinct: { meaning: "a natural, built-in impulse", example: "Fight or flight is an instinct." },
  originally: { meaning: "in the beginning", example: "The road was originally a dirt path." },
  physics: { meaning: "the science of matter and energy", example: "She studies physics at school." },
  furious: { meaning: "very angry", example: "He was furious about the dent." },
  vampires: { meaning: "mythical creatures that drink blood", example: "The movie showed vampires at night." },
  defending: { meaning: "protecting against attack", example: "The team is defending its lead." },
  decides: { meaning: "makes up the mind", example: "Mom decides what is for dinner." },
  accurate: { meaning: "correct and exact", example: "The clock is accurate." },
  suspicion: { meaning: "a feeling that something is wrong", example: "She had a suspicion about the noise." },
  confusing: { meaning: "hard to understand", example: "The sign was confusing to read." },
  generally: { meaning: "usually; mostly", example: "The buses generally run on time." },
  seeking: { meaning: "looking for", example: "She is seeking a better job." },
  secretly: { meaning: "in a hidden way", example: "He secretly planned a surprise." },
  declare: { meaning: "to state clearly and firmly", example: "I declare this fair open!" },
  missile: { meaning: "a weapon that flies to a target", example: "The missile soared over the range." },
  contacts: { meaning: "people you know; touches; lenses", example: "She forgot her contacts today." },
  maximum: { meaning: "the greatest possible amount", example: "The pool holds a maximum of ten." },
  carriage: { meaning: "a wheeled vehicle pulled by horses", example: "The carriage rolled along the lane." },
  curtain: { meaning: "a cloth that hangs over a window", example: "She pulled the curtain shut." },
  hostages: { meaning: "people held against their will", example: "The hostages were set free." },
  circles: { meaning: "perfectly round shapes", example: "The dancers moved in circles." },
  receiving: { meaning: "getting; taking in", example: "He is receiving a medal today." },
  reporters: { meaning: "people who gather the news", example: "Reporters asked questions at the scene." },
  associate: { meaning: "to connect; a partner", example: "We associate rain with clouds." },
  honesty: { meaning: "the quality of telling the truth", example: "Honesty earns trust." },
  rainbow: { meaning: "an arc of colors after rain", example: "A rainbow appeared after the storm." },
  expenses: { meaning: "costs or things you pay for", example: "Travel expenses were high." },
  discussing: { meaning: "talking about", example: "They are discussing the plan." },
  performing: { meaning: "acting or playing in front of others", example: "She is performing a dance solo." },
  retirement: { meaning: "leaving work at an older age", example: "He plans his retirement fund." },
  platform: { meaning: "a raised surface; a plan", example: "The train left from platform two." },
  illusion: { meaning: "a false image or idea", example: "The mirror trick was an illusion." },
  dentist: { meaning: "a doctor who cares for teeth", example: "The dentist cleaned my teeth." },
  lesbian: { meaning: "a woman who loves women", example: "She is honest about being a lesbian." },
  enterprise: { meaning: "a business or bold project", example: "The new enterprise opened downtown." },
  tournament: { meaning: "a series of games to find a winner", example: "The tournament begins Saturday." },
  travelling: { meaning: "going from place to place", example: "They are travelling across the country." },
  website: { meaning: "a set of pages on the internet", example: "The school website lists events." },
  mansion: { meaning: "a very large, grand house", example: "The mansion sits behind tall gates." },
  auction: { meaning: "a public sale to the highest bidder", example: "The painting sold at auction." },
  desires: { meaning: "wishes strongly for", example: "He desires a calmer life." },
  bachelor: { meaning: "an unmarried man; a degree", example: "He earned his bachelor's degree." },
  negotiate: { meaning: "to discuss to reach an agreement", example: "They tried to negotiate a deal." },
  shotgun: { meaning: "a gun with a wide barrel", example: "The farmer keeps a shotgun for pests." },
  cocktail: { meaning: "a mixed drink", example: "The bar serves a fruity cocktail." },
  pointing: { meaning: "showing with a finger or sign", example: "She is pointing at the map." },
  methods: { meaning: "ways of doing something", example: "Try different methods to solve it." },
  reference: { meaning: "a note about where information came from", example: "List a reference for that fact." },
  collapse: { meaning: "to fall down", example: "The old bridge began to collapse." },
  minimum: { meaning: "the smallest possible amount", example: "There is a minimum age to join." },
  wealthy: { meaning: "rich", example: "The wealthy family donated to the library." },
  depression: { meaning: "deep sadness; a dip in land or economy", example: "The plants grew in the depression." },
  fellows: { meaning: "men or boys; partners", example: "The fellows played cards all night." },
  password: { meaning: "a secret word to enter a place", example: "The password is written on the wall." },
  hardest: { meaning: "most difficult", example: "That was the hardest question." },
  almighty: { meaning: "all-powerful", example: "They prayed to the almighty." },
  disgrace: { meaning: "shame; loss of respect", example: "The cheating was a disgrace." },
  sources: { meaning: "places something comes from", example: "The river has two sources." },
  approval: { meaning: "agreement or permission", example: "She got her father's approval." },
  turtles: { meaning: "slow animals with shells", example: "The turtles basked on a log." },
  screech: { meaning: "a harsh, high scream", example: "The owl let out a screech." },
  legally: { meaning: "in a lawful way", example: "You can vote legally at eighteen." },
  benefits: { meaning: "good results; extra payments", example: "Exercise has many benefits." },
  domestic: { meaning: "about the home or family", example: "Housework is a domestic chore." },
  chuckle: { meaning: "to laugh quietly", example: "He gave a warm chuckle." },
  waitress: { meaning: "a woman who serves food", example: "The waitress brought our water." },
  clearing: { meaning: "an open area in a forest; removing", example: "They camped in the clearing." },
  fortunate: { meaning: "lucky", example: "We were fortunate to have good weather." },
  survivors: { meaning: "people who live through danger", example: "The survivors built a raft." },
  disappoint: { meaning: "to fail to live up to a hope", example: "Don't disappoint your team." },
  sympathy: { meaning: "feeling for another's sorrow", example: "She felt deep sympathy for the family." },
  encounter: { meaning: "a meeting; to meet", example: "We had a close encounter with a deer." },
  passenger: { meaning: "a rider in a vehicle", example: "Every passenger wore a seat belt." },
  monkeys: { meaning: "animals that climb trees", example: "The monkeys swung from branch to branch." },
  accompany: { meaning: "to go along with", example: "I will accompany you to the store." },
  pounding: { meaning: "hitting heavily; throbbing", example: "The waves were pounding the shore." },
  economic: { meaning: "about money, trade, and industry", example: "The nation faced an economic change." },
  follows: { meaning: "goes after; comes next", example: "Spring follows winter." },
  spreading: { meaning: "opening out; passing around", example: "The news is spreading quickly." },
  hilarious: { meaning: "very funny", example: "The clown's act was hilarious." },
  hallway: { meaning: "a passage between rooms", example: "The hallway was lined with pictures." },
  exclusive: { meaning: "limited to a special few", example: "The club has exclusive members." },
  decades: { meaning: "periods of ten years", example: "The bridge has stood for decades." },
  bowling: { meaning: "a game of rolling balls at pins", example: "We go bowling on Fridays." },
  buttons: { meaning: "fastenings; switches", example: "The coat has shiny buttons." },
  confusion: { meaning: "a state of being puzzled", example: "The signs caused total confusion." },
  ruining: { meaning: "spoiling completely", example: "The rain is ruining the picnic." },
  dreadful: { meaning: "very bad or unpleasant", example: "The storm left dreadful damage." },
  collecting: { meaning: "gathering things together", example: "She is collecting stamps." },
  february: { meaning: "the second month of the year", example: "February is a short month." },
  whimpers: { meaning: "soft, weak cries", example: "The puppy whimpers in its sleep." },
  sandwiches: { meaning: "food between slices of bread", example: "We packed sandwiches for the hike." },
  programme: { meaning: "a plan or broadcast (British spelling)", example: "The television programme starts at eight." },
  chemistry: { meaning: "the science of substances", example: "They mixed powders in chemistry." },
  subjects: { meaning: "topics studied in school", example: "Math and art are her favorite subjects." },
  forgiven: { meaning: "not blamed anymore", example: "The mistake was forgiven quickly." },
  phoenix: { meaning: "a mythical bird that rises from ashes", example: "A phoenix rose from the fire." },
  companion: { meaning: "a friend or partner", example: "The dog was his constant companion." },
  lottery: { meaning: "a draw for prizes", example: "They bought a lottery ticket." },
  publicity: { meaning: "attention from the public", example: "The movie got lots of publicity." },
  butterfly: { meaning: "an insect with colorful wings", example: "A butterfly landed on the rose." },
  dialogue: { meaning: "a conversation between people", example: "The dialogue between the two was heated." },
  tremendous: { meaning: "very large or great", example: "They made a tremendous effort." },
  establish: { meaning: "to set up or create", example: "They want to establish a club." },
  dearest: { meaning: "most loved; most expensive", example: "She is my dearest friend." },
  intimate: { meaning: "very close and private", example: "They shared an intimate talk." },
  contains: { meaning: "holds within itself", example: "The box contains old letters." },
  inhales: { meaning: "breathes in", example: "She inhales deeply before jumping." },
  allergic: { meaning: "harmfully sensitive to something", example: "He is allergic to bee stings." },
  gratitude: { meaning: "a feeling of thankfulness", example: "She showed gratitude for the gift." },
  exception: { meaning: "a case that doesn't follow the rule", example: "Everyone came, with one exception." },
  ultimately: { meaning: "in the end; finally", example: "Ultimately, the plan worked." },
  compromise: { meaning: "to settle by giving up a little", example: "They reached a fair compromise." },
  majority: { meaning: "more than half", example: "The majority voted yes." },
  journal: { meaning: "a daily record or diary", example: "She writes in her journal each night." },
  signals: { meaning: "signs or messages", example: "Smoke signals rose from the hill." },
  essential: { meaning: "completely necessary", example: "Water is essential for life." },
  climate: { meaning: "the usual weather of a place", example: "This region has a warm climate." },
  magazines: { meaning: "periodical journals with articles", example: "The magazines are stacked on the table." },
  passionate: { meaning: "full of strong feeling", example: "She is passionate about music." },
  precise: { meaning: "exact and accurate", example: "Follow the precise measurements." },
  murmuring: { meaning: "speaking softly and quietly", example: "The stream is murmuring nearby." },
  capacity: { meaning: "the amount something can hold", example: "The hall is at full capacity." },
  opponent: { meaning: "a person on the other side", example: "Her opponent was a fast runner." },
  instrument: { meaning: "a tool; a music device", example: "The violin is a difficult instrument." },
  healing: { meaning: "becoming well again", example: "Rest is part of healing." },
  convention: { meaning: "a large meeting; a custom", example: "Fan conventions draw big crowds." },
  messenger: { meaning: "a person who carries messages", example: "The messenger delivered an urgent note." },
  explore: { meaning: "to travel and discover", example: "We will explore the old cave." },
  survivor: { meaning: "one who lives through danger", example: "He is the lone survivor of the crash." },
  experts: { meaning: "people with deep knowledge", example: "Experts agree the sky is blue." },
  disguise: { meaning: "a costume to hide identity", example: "The spy wore a clever disguise." },
  bicycle: { meaning: "a two-wheeled pedaled vehicle", example: "She rode her bicycle to school." },
  inviting: { meaning: "asking; welcoming", example: "He is inviting everyone to the party." },
  pregnancy: { meaning: "the state of expecting a baby", example: "Exercise helps during pregnancy." },
  innocence: { meaning: "freedom from guilt; purity", example: "The child's innocence was clear." },
  creaking: { meaning: "making a squeaking noise", example: "The old stairs were creaking." },
  painter: { meaning: "one who paints", example: "The painter finished the rooms." },
  sickness: { meaning: "illness", example: "Rest helps you recover from sickness." },
  civilian: { meaning: "a person not in the military", example: "The soldier greeted a civilian." },
  fighters: { meaning: "people who fight; warplanes", example: "The fighters trained all day." },
  customs: { meaning: "taxes on goods; traditions", example: "We waited at customs with our bags." },
  remembers: { meaning: "keeps in memory", example: "She remembers her first day of school." },
  seventh: { meaning: "the one after the sixth", example: "The seventh floor has a garden." },
  avoiding: { meaning: "staying away from", example: "He is avoiding the puddles." },
  household: { meaning: "a family unit in a home", example: "The whole household pitched in." },
  cracking: { meaning: "making a sharp sound; breaking", example: "The ice was cracking underfoot." },
  harmless: { meaning: "causing no harm", example: "The garden snake is harmless." },
  curiosity: { meaning: "a strong wish to know", example: "Curiosity led her to open the book." },
  vicious: { meaning: "cruel and fierce", example: "The vicious storm tore branches down." },
  officials: { meaning: "people in authority", example: "The officials announced the winner." },
  nearest: { meaning: "closest in distance", example: "The nearest store is a mile away." },
};